### ISSUE TITLE
t2 update crashes upon downloading files

### ISSUE THREAD

**Issue by afhaque** [tessel/t2-cli#1044]
Running into an issue with the t2 update process. 

Currently on: 
t2-cli: 0.1.0. 
t2-firmware: 0.0.13. 
Node: 4.4.3 (<- this number stuck even when I upgraded node to 4.6.0).

Output below:
$ t2 update
INFO Looking for your Tessel...
INFO Connected to LilAhmy.
INFO New firmware version found...0.0.16
INFO Updating LilAhmy to latest version (0.0.16)...
INFO Downloading files...
ERR! Detected CLI crash [TypeError: this.stream.clearLine is not a function] TypeError: this.stream.clearLine is not a function
ERR!     at ProgressBar.terminate (C:\Users\afhaq\AppData\Roaming\npm\node_modules\t2-cli\node_modules\progress\lib\node-progress.js:177:17)
ERR!     at ProgressBar.tick (C:\Users\afhaq\AppData\Roaming\npm\node_modules\t2-cli\node_modules\progress\lib\node-progress.js:91:10)
ERR!     at IncomingMessage.<anonymous> (C:\Users\afhaq\AppData\Roaming\npm\node_modules\t2-cli\lib\update-fetch.js:182:13)
ERR!     at emitOne (events.js:82:20)
ERR!     at IncomingMessage.emit (events.js:169:7)
ERR!     at IncomingMessage.Readable.read (_stream_readable.js:368:10)
ERR!     at flow (_stream_readable.js:759:26)
ERR!     at Gunzip.<anonymous> (_stream_readable.js:616:7)
ERR!     at emitNone (events.js:67:13)
ERR!     at Gunzip.emit (events.js:166:7)
INFO Download complete!
ERR! TypeError: Cannot read property 'length' of undefined

**Comment by tcr** [comment]
Hm, we've gotten crash reports for this issue before.

@rwaldron I think this PR fixes the issue by checking if stderr is a TTY before `.terminate` (which it doesn't fail to check at the beginning of the `.render` function): https://github.com/visionmedia/node-progress/pull/99 However, node-progress hasn't been updated in a year, so I'm concerned that PR won't make it upstream.

We can recreate this error by forcing stdout to be a stream. Save as `index.js`:

```
var Progress = require('progress');

// Create a new progress bar
var bar = new Progress('     [:bar] :percent :etas remaining', {
  clear: true,
  complete: '=',
  incomplete: ' ',
  width: 20,
  total: 100,
  stream: process.stdout,
});

bar.update(0.5);

// When we get incoming data, update the progress bar
setTimeout(() => {
  bar.update(1.0);
}, 1000);
```

Then run `node test.js | cat`:

`
$
/Users/tim/tessel/t2-cli/node_modules/progress/lib/node-progress.js:177
    this.stream.clearLine();
                ^

TypeError: this.stream.clearLine is not a function
    at ProgressBar.terminate (/Users/tim/tessel/t2-cli/node_modules/progress/lib/node-progress.js:177:17)
    at ProgressBar.tick (/Users/tim/tessel/t2-cli/node_modules/progress/lib/node-progress.js:91:10)
    at ProgressBar.update (/Users/tim/tessel/t2-cli/node_modules/progress/lib/node-progress.js:166:8)
    at Timeout.setTimeout (/Users/tim/tessel/t2-cli/test.js:17:7)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

**Comment by rwaldron** [comment]
What shell/terminal/command-line program are you using?

**Comment by rwaldron** [comment]
> Node: 4.4.3 (<- this number stuck even when I upgraded node to 4.6.0).

That's the version _on_ the board, not your local Node.js
